language: rust

cache: cargo

before_install:
    - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.0.12.tgz
    - tar xvf mongodb-linux-x86_64-3.0.12.tgz
    - mv mongodb-linux-x86_64-3.0.12 3.0.12
    - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.2.10.tgz
    - tar xvf mongodb-linux-x86_64-3.2.10.tgz
    - mv mongodb-linux-x86_64-3.2.10 3.2.10

env:
    - RUST_TEST_THREADS=1

script:
    - mkdir -p ./data/db ./data/test ./data/db2 ./data/test2
    - 3.0.12/bin/mongod --fork --nopreallocj --dbpath ./data/db --syslog --port 27017
    - 3.0.12/bin/mongod --fork --nopreallocj --dbpath ./data/test --syslog --port 27018
    - cargo build --verbose
    - cargo test --features "mongodb_3_0" --verbose
    - killall mongod
    - 3.2.10/bin/mongod --fork --nopreallocj --dbpath ./data/db2 --syslog --port 27017
    - 3.2.10/bin/mongod --fork --nopreallocj --dbpath ./data/test2 --syslog --port 27018
    - cargo test --verbose
