language: rust

before_script:
    - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.0.3.tgz
    - tar xvf mongodb-linux-x86_64-3.0.3.tgz
    - mv mongodb-linux-x86_64-3.0.3 3.0.3

env:
    - RUST_TEST_THREADS=1

script:
    - mkdir -p ./data/db
    - 3.0.3/bin/mongod --fork --nopreallocj --dbpath ./data/db --syslog
    - cargo build --verbose
    - cargo test --verbose