[package]
name = "mongodb"
version = "0.1.0"
authors = ["Valeri Karpov <valkar207@gmail.com>",
           "Saghm Rossi <saghmrossi@gmail.com>",
           "Kevin Yeh <kevinyeah@utexas.edu>"]

[dependencies]
byteorder = "0.3.10"
bson-rs = "0.1.0"
