[package]
name = "mongodb"
version = "0.1.0"
authors = ["Valeri Karpov <valkar207@gmail.com>",
           "Saghm Rossi <saghmrossi@gmail.com>",
           "Kevin Yeh <kevinyeah@utexas.edu>"]

[dependencies]
byteorder = "0.3"
chrono = "0.2"
libc = "0.1"
nalgebra = "0.2"
rand = "0.3"
rust-crypto = "0.2.31"
rustc-serialize = "0.3"
time = "0.1"

[dependencies.bson]
git = "https://github.com/zonyitoo/bson-rs"
ref = "1c1fcca2781f6a8947bbf1abe7b4bcbfba9e7ee3"
