[package]
name = "mongodb"
version = "0.1.0"
authors = ["Valeri Karpov <valkar207@gmail.com>",
           "Saghm Rossi <saghmrossi@gmail.com>",
           "Kevin Yeh <kevinyeah@utexas.edu>"]
description = "An experimental MongoDB driver written by MongoDB interns."
repository = "https://github.com/mongodbinc-interns/mongo-rust-driver-prototype"
readme = "README.md"
keywords = ["mongo", "mongodb", "database", "bson", "nosql"]
license = "apache"

[dependencies]
bson = "0.1.3"
byteorder = "0.3"
chrono = "0.2"
rand = "0.3"
rust-crypto = "0.2.31"
rustc-serialize = "0.3"
scan_fmt = "0.1.0"
separator = "0.3.0"
textnonce = "0.1.1"
time = "0.1"

[dev-dependencies]
nalgebra = "0.2"
